# Generated by Django 5.0.1 on 2024-01-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotWheelz', '0003_remove_owner_collections_owner_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='collections',
            new_name='collection',
        ),
    ]
