# Generated by Django 5.0.1 on 2024-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotWheelz', '0005_collection_name_alter_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='owner_name',
        ),
    ]
